apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-kube-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: argocd-kube
  template:
    metadata:
      labels:
        run: argocd-kube
    spec:
      containers:
      - image: 982534393351.dkr.ecr.ap-northeast-2.amazonaws.com/web-site:6ebb4d3
        name: argocd-kube
